export const TEXT = {
  en: {
    nav: { about: 'About Us', services: 'Services', residents: 'Residents', happiness: 'Happiness', programs: 'Daily Activities', gallery: 'Gallery', volunteer: 'Volunteer', contact: 'Contact' },
    lang: 'English / हिंदी',
    heroBadge: 'Serving Since 2008',
    heroLead: 'Because Every Elder Deserves to',
    heroEmphasis: 'Feel at Home',
    heroSub: 'Providing dignified, compassionate, and community-supported care for 340+ elders across Delhi NCR. Join us in making aging a celebration.',
    donate: 'Donate Now',
    story: 'Watch Our Story',
    trust: ['80G Certified', 'FCRA Registered', '17 Years of Service', 'English + Hindi Support'],
    residentLabel: 'Our Community',
    residentTitle: 'Life at Samarth Foundation',
    residentSub: 'We believe that an old age home should not be a waiting room for the end of life, but a vibrant community where elders can celebrate their golden years with dignity, joy, and companionship.',
    happinessLabel: 'Monthly Happiness Feed',
    happinessTitle: 'What Our Residents Say',
    happinessSub: 'Direct stories and voices from the elders living in our warm community.',
    donateLabel: 'Make an Impact',
    donateTitle: 'Your Gift Changes Lives',
    donateSub: 'Just ₹500 provides a month of warm, nutritious meals for an elder. All donations are 100% transparent and eligible for 80G tax exemption.',
    volunteerLabel: 'Join Our Community',
    volunteerTitle: 'Share Your Time. Change a Life.',
    volunteerSub: 'Our volunteers are the heartbeat of Samarth Foundation. Whether you have 2 hours a week or can join for special events, your presence brings immense joy to our residents.',
    contentLabel: 'Content And Admin',
    contentTitle: 'Stories Need A Clear Workflow',
    contentSub: 'The final site needs resident stories, short videos, and approvals that team members can manage without editing raw HTML.',
    accessibilityLabel: 'Language And Accessibility',
    accessibilityTitle: 'Built For English And Hindi',
    accessibilitySub: 'The plan calls for bilingual content, readable typography, keyboard support, and checks that keep the layout stable on mobile and desktop.',
    servicesLabel: 'What We Provide',
    servicesTitle: 'Complete Care, Every Day',
    servicesSub: 'We offer a full spectrum of professional services designed to nurture physical health, emotional wellbeing, and community connection for every resident.',
    programsLabel: 'Daily Life',
    programsTitle: 'Programs That Bring Joy',
    programsSub: 'From morning yoga to evening cultural programs, every day at Samarth Foundation is designed to nurture the mind, body, and spirit.',
    journeyLabel: 'Our Journey',
    journeyTitle: 'Recent Celebrations & Highlights',
    journeySub: 'Every month brings new celebrations, milestones, and moments of connection. Here are some highlights from our community.',
    galleryLabel: 'Gallery',
    galleryTitle: 'Life in Pictures',
    gallerySub: 'A glimpse into the warmth, joy, and community of Samarth Foundation — captured in real moments.',
    instaLabel: 'Follow Our Journey',
    instaTitle: 'We Are on Instagram',
    instaHandle: '@samarthngo',
    contactLabel: 'Contact',
    contactTitle: 'Talk To The Team',
    contactSub: 'Use the form for donation questions, volunteer requests, resident story submissions, or general support.',
    contactDetails: 'Contact Details',
    contactNext: 'What Happens Next',
    contactNote: 'Messages route to the right owner: donations, volunteer intake, content, or operations. That keeps the workflow aligned with the team plan in the docs.',
    contactButton: 'Send Message',
    volunteerButton: 'Apply Now',
    newsletterButton: 'Subscribe',
    donateSecure: 'Donate Securely',
    donateTabs: ['Monthly', 'One-Time'],
    galleryFilters: { all: 'All', celebration: 'Celebrations', wellness: 'Wellness', healthcare: 'Healthcare', activities: 'Activities' },
    contactReason: 'Reason For Contact',
    contactPlaceholder: 'Choose one',
    contactReasons: ['Donation', 'Volunteer', 'Resident Story', 'General Query'],
    contactName: 'Your Name',
    contactEmail: 'Email Address',
    contactMessage: 'Message',
    volunteerEmail: 'Your Email Address',
    residentQuote: 'I thought I had lost my family, but here, I found a new one. I laugh more now than I have in years.',
    residentAttribution: 'Shanti Devi, 72',
    accessibilityChecks: ['Check contrast, touch targets, and readable line lengths.', 'Keep labels, placeholders, and form hints clear on small screens.', 'Verify language switching does not break the layout.', 'Test keyboard navigation before release.'],
    adminLabel: 'Login And Admin',
    adminTitle: 'Functional Team Workspace',
    adminSub: 'Use the local demo login to review submissions, publish resident stories, and inspect the queued backend records without editing raw HTML.',
    adminEmail: 'Admin Email',
    adminPassword: 'Password',
    adminLogin: 'Sign In',
    adminLogout: 'Sign Out',
    adminStoryTitle: 'Add Resident Story',
    adminStoryName: 'Resident Name',
    adminStoryQuote: 'Story Quote',
    adminStoryImage: 'Image URL',
    adminStoryVideo: 'Video URL',
    adminStorySave: 'Save Story',
    dashboardTitle: 'Impact Dashboard',
    dashboardSub: 'This dashboard aggregates the local submission queue. It is functional in-browser and ready to be replaced by a real API later.',
    backendLabel: 'Backend Integration',
    backendTitle: 'Local Queue Simulation',
    backendSub: 'Contact, volunteer, newsletter, donation, and story entries are stored in browser localStorage to model the expected backend workflow.',
    donationFlowTitle: 'Donation Flow',
    donationFlowSub: 'Choose an amount, provide donor details, and submit to the local queue. This is a working client-side simulation of the planned donation pipeline.',
    donationName: 'Donor Name',
    donationEmail: 'Donor Email',
    donationNote: 'Donation Note',
    donationSubmit: 'Complete Donation',
    communityLabel: 'Community Engagement',
    communityTitle: 'Showcase Activities From The Docs',
    communitySub: 'Open mic, children interaction, and community engagement are represented here as part of the planned resident activity showcase.',
    workflowCards: [
      ['Story', 'Resident Story CMS Pattern', 'Use repeatable story cards for text, photos, captions, and short videos so the team can publish updates consistently.', 'Ready for CMS handoff'],
      ['Lock', 'Admin Panel And Roles', 'Define who can draft, review, and publish content, plus how login access maps to content ownership and moderation.', 'Login + approval workflow'],
      ['Users', 'Team Ownership', 'Keep content, media, forms, and backend workstreams separate so the team can review progress weekly and ship safely.', 'Weekly review cadence']
    ]
  },
  hi: {
    nav: { about: 'हमारे बारे में', services: 'सेवाएँ', residents: 'निवासी', happiness: 'संतुष्टि', programs: 'दैनिक गतिविधियां', gallery: 'गैलरी', volunteer: 'स्वयंसेवा', contact: 'संपर्क' },
    lang: 'हिंदी / English',
    heroBadge: '2008 से सेवा',
    heroLead: 'क्योंकि हर बुज़ुर्ग को',
    heroEmphasis: 'घर जैसा महसूस होना चाहिए',
    heroSub: '340+ बुज़ुर्गों के लिए सम्मानजनक, करुणामय और समुदाय-समर्थित देखभाल। आइए उम्र बढ़ने को एक उत्सव बनाएं।',
    donate: 'दान करें',
    story: 'हमारी कहानी देखें',
    trust: ['80G प्रमाणित', 'FCRA पंजीकृत', '17 वर्षों की सेवा', 'English + Hindi समर्थन'],
    residentLabel: 'हमारा समुदाय',
    residentTitle: 'समर्थ आश्रम में जीवन',
    residentSub: 'हम मानते हैं कि old age home जीवन के अंत की प्रतीक्षा करने की जगह नहीं, बल्कि एक जीवंत समुदाय होना चाहिए जहाँ बुज़ुर्ग गरिमा, खुशी और साथ का अनुभव करें।',
    coupon: 'कूपन',
    donateLabel: 'प्रभाव डालें',
    donateTitle: 'आपका सहयोग जीवन बदलता है',
    donateSub: 'केवल ₹500 एक बुज़ुर्ग के लिए एक महीने के गरम, पौष्टिक भोजन प्रदान करता है। सभी दान 100% पारदर्शी हैं और 80G tax exemption के पात्र हैं।',
    volunteerLabel: 'हमारे समुदाय से जुड़ें',
    volunteerTitle: 'अपना समय साझा करें. एक जीवन बदलें.',
    volunteerSub: 'हमारे स्वयंसेवक Samarth Foundation की धड़कन हैं। चाहे आपके पास हफ्ते में 2 घंटे हों या विशेष कार्यक्रमों में शामिल हो सकें, आपकी उपस्थिति हमारे निवासियों के लिए बड़ी खुशी लाती है।',
    contentLabel: 'सामग्री और एडमिन',
    contentTitle: 'कहानियों के लिए स्पष्ट workflow चाहिए',
    contentSub: 'अंतिम साइट में resident stories, short videos, और approvals ऐसे हों कि टीम raw HTML बदले बिना content manage कर सके।',
    accessibilityLabel: 'भाषा और पहुँचनीयता',
    accessibilityTitle: 'English और Hindi के लिए तैयार',
    accessibilitySub: 'योजना bilingual content, readable typography, keyboard support, और mobile/desktop पर stable layout पर केंद्रित है।',
    servicesLabel: 'हम क्या प्रदान करते हैं',
    servicesTitle: 'हर दिन सम्पूर्ण देखभाल',
    servicesSub: 'हमारी सेवाएँ शारीरिक स्वास्थ्य, भावनात्मक wellbeing, और समुदायिक जुड़ाव को पोषित करने के लिए हैं।',
    programsLabel: 'दैनिक जीवन',
    programsTitle: 'खुशी लाने वाले कार्यक्रम',
    programsSub: 'सुबह योग से शाम के सांस्कृतिक कार्यक्रमों तक, हर दिन मन, शरीर और आत्मा को पोषण देने के लिए बनाया गया है।',
    journeyLabel: 'हमारी यात्रा',
    journeyTitle: 'हाल के उत्सव और मुख्य आकर्षण',
    journeySub: 'हर महीने नई celebrations, milestones, और connection के पल आते हैं।',
    galleryLabel: 'गैलरी',
    galleryTitle: 'तस्वीरों में जीवन',
    gallerySub: 'Samarth Foundation की गर्माहट, खुशी, और community की झलक — वास्तविक क्षणों में।',
    instaLabel: 'हमारी यात्रा फ़ॉलो करें',
    instaTitle: 'हम Instagram पर हैं',
    instaHandle: '@samarthngo',
    contactLabel: 'संपर्क',
    contactTitle: 'टीम से बात करें',
    contactSub: 'दान, स्वयंसेवा, resident story submissions, या सामान्य सहायता के लिए फ़ॉर्म का उपयोग करें।',
    contactDetails: 'संपर्क विवरण',
    contactNext: 'आगे क्या होगा',
    contactNote: 'संदेश सही owner तक पहुँचते हैं: donations, volunteer intake, content, या operations. इससे docs के अनुसार workflow aligned रहता है।',
    contactButton: 'संदेश भेजें',
    volunteerButton: 'अभी आवेदन करें',
    newsletterButton: 'सदस्यता लें',
    donateSecure: 'सुरक्षित दान करें',
    donateTabs: ['मासिक', 'एक बार'],
    galleryFilters: { all: 'सभी', celebration: 'उत्सव', wellness: 'स्वास्थ्य', healthcare: 'चिकित्सा', activities: 'गतिविधियाँ' },
    contactReason: 'संपर्क का कारण',
    contactPlaceholder: 'एक चुनें',
    contactReasons: ['दान', 'स्वयंसेवा', 'निवासी कहानी', 'सामान्य प्रश्न'],
    contactName: 'का नाम',
    contactEmail: 'ईमेल पता',
    contactMessage: 'संदेश',
    volunteerEmail: 'आपका ईमेल पता',
    residentQuote: 'मुझे लगा था कि मैंने अपना परिवार खो दिया है, लेकिन यहाँ मुझे एक नया परिवार मिला। अब मैं पहले से कहीं ज़्यादा हँसती हूँ।',
    residentAttribution: 'शांति देवी, 72',
    accessibilityChecks: ['Contrast, touch targets, और readable line lengths की जाँच करें।', 'Labels, placeholders, और form hints छोटे स्क्रीन पर साफ़ रखें।', 'Language switch से layout न बिगड़े, यह verify करें।', 'Release से पहले keyboard navigation test करें।'],
    adminLabel: 'लॉगिन और एडमिन',
    adminTitle: 'Functional Team Workspace',
    adminSub: 'Local demo login से submissions review करें, resident stories publish करें, और queued backend records देखें — raw HTML बदले बिना।',
    adminEmail: 'Admin Email',
    adminPassword: 'Password',
    adminLogin: 'Sign In',
    adminLogout: 'Sign Out',
    adminStoryTitle: 'Resident Story जोड़ें',
    adminStoryName: 'Resident Name',
    adminStoryQuote: 'Story Quote',
    adminStoryImage: 'Image URL',
    adminStoryVideo: 'Video URL',
    adminStorySave: 'Save Story',
    dashboardTitle: 'Impact Dashboard',
    dashboardSub: 'यह dashboard local submission queue को aggregate करता है। यह browser में functional है और आगे real API से replace किया जा सकता है।',
    backendLabel: 'Backend Integration',
    backendTitle: 'Local Queue Simulation',
    backendSub: 'Contact, volunteer, newsletter, donation, और story entries browser localStorage में सेव होती हैं ताकि expected backend workflow simulate हो सके।',
    donationFlowTitle: 'Donation Flow',
    donationFlowSub: 'Amount चुनें, donor details भरें, और local queue में submit करें। यह planned donation pipeline का working client-side simulation है।',
    donationName: 'Donor Name',
    donationEmail: 'Donor Email',
    donationNote: 'Donation Note',
    donationSubmit: 'Complete Donation',
    communityLabel: 'Community Engagement',
    communityTitle: 'Docs से Activities Showcase',
    communitySub: 'Open mic, children interaction, और community engagement को resident activity showcase के रूप में यहाँ दिखाया गया है।',
    coupon: 'कूपन',
    volunteerTitle: 'अपना समय साझा करें. एक जीवन बदलें.',
    volunteerSub: 'हमारे स्वयंसेवक Samarth Foundation की धड़कन हैं। चाहे आपके पास हफ्ते में 2 घंटे हों या विशेष कार्यक्रमों में शामिल हो सकें, आपकी उपस्थिति हमारे निवासियों के लिए बड़ी खुशी लाती है।',
    workflowCards: [
      ['Story', 'Resident Story CMS Pattern', 'Text, photos, captions, और short videos के लिए repeatable cards रखें ताकि team consistent updates publish कर सके।', 'CMS handoff ready'],
      ['Lock', 'Admin Panel और Roles', 'कौन draft, review, और publish कर सकता है — इसे define करें, साथ ही login access और moderation mapping तय करें।', 'Login + approval workflow'],
      ['Users', 'टीम Ownership', 'Content, media, forms, और backend workstreams को अलग रखें ताकि weekly review में progress सुरक्षित रहे।', 'Weekly cadence']
    ]
  }
};

export const CURATED_ICONS = [
  'Hospital', 'Accommodation', 'Recreation', 'Yoga', 'Music', 'Leaf', 'Smile', 'Heart', 'Coffee', 'User', 'Doctor', 'Medicine'
];

export const donationAmounts = [
  [500, 'Meals for 1 month'],
  [1000, 'Medical Care'],
  [2500, 'Full Sponsorship']
];

export const fallbackActivities = [
  { id: 'act-1', titleEn: 'Daily Yoga & Meditation', titleHi: 'दैनिक योग और ध्यान', descEn: 'Gentle morning stretching, pranayama, and mindfulness sessions to improve flexibility and reduce anxiety.', descHi: 'लचीलापन बढ़ाने और चिंता को कम करने के लिए सुबह की कोमल स्ट्रेचिंग, प्राणायाम और ध्यान सत्र।', icon: 'Yoga' },
  { id: 'act-2', titleEn: 'Light Exercise & Physiotherapy', titleHi: 'हल्का व्यायाम और फिजियोथेरेपी', descEn: 'Guided low-impact walking and customized movement exercises to maintain muscle strength and joint mobility.', descHi: 'मांपेशियों की ताकत और जोड़ों की गतिशीलता को बनाए रखने के लिए निर्देशित कम प्रभाव वाले चलने और अनुकूलित आंदोलन अभ्यास।', icon: 'Smile' },
  { id: 'act-3', titleEn: 'Recreational Arts & Crafts', titleHi: 'मनोरंजक कला और शिल्प', descEn: 'Creative cognitive stimulation through art workshops, embroidery, and puzzle-solving groups.', descHi: 'कला कार्यशालाओं, कढ़ाई और पहेली-सुलझाने वाले समूहों के माध्यम से रचनात्मक संज्ञानात्मक उत्तेजना।', icon: 'Recreation' },
  { id: 'act-4', titleEn: 'Nutritional Diet Planning', titleHi: 'पौष्टिक आहार योजना', descEn: 'Regular consultations to adjust meal plans based on individual medical needs like diabetic and low-sodium diets.', descHi: 'मधुमेह और कम सोडियम वाले आहार जैसी व्यक्तिगत चिकित्सा आवश्यकताओं के आधार पर भोजन योजनाओं को समायोजित करने के लिए नियमित परामर्श।', icon: 'Medicine' }
];

export const fallbackServices = [
  { id: 'srv-1', titleEn: '24/7 Dedicated Caregiving', titleHi: '24/7 समर्पित देखभाल', descEn: 'Round-the-clock assistance with mobility, personal hygiene, and medicine management by trained staff.', descHi: 'प्रशिक्षित कर्मचारियों द्वारा चलने-फिरने, व्यक्तिगत स्वच्छता और दवा प्रबंधन में चौबीसों घंटे सहायता।', icon: 'Accommodation' },
  { id: 'srv-2', titleEn: 'Doctor-on-Call & Medical Care', titleHi: 'Doctor-on-Call और चिकित्सा देखभाल', descEn: 'Daily vital health tracking, regular checkups, and immediate ambulance/doctor dispatch for emergency assistance.', descHi: 'आपातकालीन सहायता के लिए दैनिक महत्वपूर्ण स्वास्थ्य ट्रैकिंग, नियमित जांच और तत्काल एम्बुलेंस / डॉक्टर प्रेषण।', icon: 'Hospital' },
  { id: 'srv-3', titleEn: 'Nutritious Diet plans', titleHi: 'पौष्टिक आहार योजनाएं', descEn: "Freshly cooked pure-vegetarian meals customized to residents' medical conditions.", descHi: 'निवासियों की स्वास्थ्य स्थितियों के अनुरूप तैयार ताजा शाकाहारी भोजन।', icon: 'Coffee' },
  { id: 'srv-4', titleEn: 'Counseling & Social Support', titleHi: 'परामर्श और सामाजिक सहायता', descEn: 'Individual counseling, group therapy, and community engagement to combat loneliness and boost morale.', descHi: 'अकेलेपन से निपटने और मनोबल बढ़ाने के लिए व्यक्तिगत परामर्श, समूह चिकित्सा और सामुदायिक जुड़ाव।', icon: 'User' }
];

export const fallbackTestimonials = [
  { id: 'tst-1', nameEn: 'Shanti Devi', nameHi: 'शांति देवी', age: 72, quoteEn: 'I was lonely living by myself, but now I do yoga every morning with friends.', quoteHi: 'मैं अकेली रहती थी और अकेलापन महसूस करती थी, लेकिन अब मैं यहाँ दोस्तों के साथ रोज़ सुबह योग करती हूँ।', isAnonymous: false },
  { id: 'tst-2', nameEn: 'Ramesh Kumar', nameHi: 'रमेश कुमार', age: 68, quoteEn: 'The doctors check my blood pressure daily, and the meals are fresh and pure vegetarian.', quoteHi: 'डॉक्टर रोज़ मेरी सेहत की जांच करते हैं, और यहाँ मिलने वाला भोजन एकदम ताज़ा और शुद्ध शाकाहारी है।', isAnonymous: false },
  { id: 'tst-3', nameEn: 'Meera Sharma', nameHi: 'मीरा शर्मा', age: 70, quoteEn: 'My family lives far, but here I feel safe, loved, and physically active.', quoteHi: 'मेरा परिवार दूर रहता है, लेकिन यहाँ मैं सुरक्षित, स्नेही और शारीरिक रूप से सक्रिय महसूस करती हूँ।', isAnonymous: false }
];

export const fallbackEvents = [
  { id: 'evt-1', slug: 'diwali-celebration-2026', titleEn: 'Diwali Celebration 2026', titleHi: 'दिवाली उत्सव 2026', date: '2026-11-10', descEn: 'A night of lamps, prayers, and sweets with residents and family members.', descHi: 'निवासियों और परिवार के सदस्यों के साथ दीयों, प्रार्थनाओं और मिठाइयों की शाम।', status: 'Published', relatedActivityId: 'act-1', image: 'https://images.unsplash.com/photo-1605647540924-852290f6b0d5?auto=format&fit=crop&w=600&q=80' },
  { id: 'evt-2', slug: 'yoga-wellness-camp', titleEn: 'Yoga & Wellness Camp', titleHi: 'योग और कल्याण शिविर', date: '2026-06-15', descEn: 'Morning meditation and breathing exercises with local yoga specialists.', descHi: 'स्थानीय योग विशेषज्ञों के साथ सुबह का ध्यान और साँस लेने का व्यायाम।', status: 'Published', relatedActivityId: 'act-1', image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=600&q=80' },
  { id: 'evt-3', slug: 'nutrition-week-drive', titleEn: 'Nutrition Week Meetup', titleHi: 'पोषण सप्ताह बैठक', date: '2026-09-08', descEn: 'A specialized dietary guidelines session and recipe sharing for residents.', descHi: 'निवासियों के लिए एक विशेष आहार दिशानिर्देश सत्र और नुस्खा साझा करना।', status: 'Published', relatedActivityId: 'act-4', image: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=600&q=80' }
];

export const assets = {
  hero: new URL('../assets/images/hero.png', import.meta.url).href,
  community: new URL('../assets/images/community.png', import.meta.url).href,
  volunteer: new URL('../assets/images/volunteer.png', import.meta.url).href,
  galleryCelebration: new URL('../assets/images/gallery_celebration.png', import.meta.url).href,
  galleryMedical: new URL('../assets/images/gallery_medical.png', import.meta.url).href,
  galleryYoga: new URL('../assets/images/gallery_yoga.png', import.meta.url).href,
  galleryArt: new URL('../assets/images/gallery_art.png', import.meta.url).href
};

export const policyContent = {
  privacy: {
    title: 'Privacy Policy',
    body: 'Your privacy is important to us. It is Samarth Foundation\'s policy to respect your privacy regarding any information we may collect from you across our website. We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used. We only retain collected information for as long as necessary to provide you with your requested service.'
  },
  terms: {
    title: 'Terms of Service',
    body: 'By accessing our website, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.'
  }
};
